# _config.yml
url: https://swasilan.github.io/esphome-epson-eh-tw3200-rs232/
# remote_theme: just-the-docs/just-the-docs
remote_theme: artemsheludko/flexible-jekyll
title: "Jekyll Actions Demo"


# Author Settings
author: Sascha Waser
author-img: _DSC2403.jpg
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: artemsheludko # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"
